language: scala

os:
  - linux
  - osx

scala:
  - "2.12.7"

jdk: oraclejdk8

env:
  - TRAVIS_NODE_VERSION="10.10.0"

install:
  - source travis/setNodeVersion.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - wget http://central.maven.org/maven2/org/scala-sbt/launcher/1.0.4/launcher-1.0.4.jar
  - java -Xms512m -Xmx1536m -Xss2m -jar ./launcher-1.0.4.jar -Dsbt.boot.properties=./project/boot.properties ++$TRAVIS_SCALA_VERSION test deploy
  # re-using current sbtcli version to recompile the current scala project
  - ./bin/sbtcli --ll trace clean compile
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
